"""Type definitions for the OptiChat system."""

from typing import Any, Dict, List, NamedTuple, Set, Union

import pyomo.environ as pe
from openai.types.chat import ChatCompletionMessageParam
from typing_extensions import NotRequired, TypedDict


class TeamConversationMessage(TypedDict):
    """
    Type definition for team conversation messages.

    Attributes
    ----------
    agent_name : str
        The name of the agent that generated the message.
    agent_response : str
        The response content from the agent.
    """

    agent_name: str
    agent_response: str


class DecisionDict(TypedDict):
    """
    Type definition for coordinator decision dictionaries.

    Used by the Coordinator agent to specify which agent should work next
    and what task they should perform.

    Attributes
    ----------
    agent_name : str
        The name of the agent to call next (e.g., "Engineer", "Explainer").
    task : str
        The task for the agent to carry out. Can be "DONE" to indicate completion.
    """

    agent_name: str
    task: str


class QueriedComponent(TypedDict):
    """
    Type definition for queried component dictionaries with modification operations.

    Extends QueriedComponent to include operation and delta fields used by
    evaluate_modification function for parameter modifications.

    Attributes
    ----------
    component_name : str
        The name of the component (e.g., "dem", "supply", "cost").
    component_indexes : None | str | int | list[str | int] | tuple[str | int] | slice
        The indexes to specify which component instances to target.
    operation : str
        The modification operation: "=" (set to), "+" (add), "-" (subtract),
        "*" (multiply), "/" (divide), or "!" (no operation specified).
    delta : float | int
        The extent of the modification. For operation "!", delta should be 0.
    """

    component_name: str
    component_indexes: (
        None | str | int | List[Union[str, int]] | tuple[Union[str, int], ...] | slice
    )
    operation: NotRequired[str]
    delta: NotRequired[Union[float, int]]


class ExecutionResult(NamedTuple):
    """
    Return type for the execute_code method.

    Attributes
    ----------
    source_code : str
        The complete source code after combining original source with revision code.
    execution_output : str
        The output/result from executing the code.
    """

    source_code: str
    execution_output: str


class SyntaxGuidanceResult(NamedTuple):
    """
    Return type for the generate_syntax_exp method.

    Attributes
    ----------
    syntax_output : str
        The syntax guidance text and reminders for technical analysis tools.
    syntax_mode : str
        The syntax analysis mode ("single", "multiple", "none") indicating
        the type of component indexing available.
    """

    syntax_output: str
    syntax_mode: str


class InterpretationResult(NamedTuple):
    """
    Return type for the generate_interpretation_exp method.

    Attributes
    ----------
    models_dict : ModelsContainer
        Updated models dictionary with component descriptions.
    retry_count : int
        Number of retry attempts remaining.
    task_complete : bool
        Flag indicating whether the interpretation task completed successfully.
    """

    models_dict: "ModelsContainer"
    retry_count: int
    task_complete: bool


class CoordinationResult(NamedTuple):
    """
    Return type for the generate_decision method.

    Attributes
    ----------
    status : str
        Status of coordination ("In Progress", "Completed", "Terminated").
    result : str | DecisionDict
        Either the final output string or the decision dictionary.
    """

    status: str
    result: "str | DecisionDict"


class ProgrammerResult(NamedTuple):
    """
    Return type for the programmer_loop_exp method.

    Attributes
    ----------
    code_output : str | None
        The complete code output generated by the programmer.
    revision_code : str | None
        The code modifications to be applied.
    print_code : str | None
        The code for printing/display purposes.
    """

    code_output: str | None
    revision_code: str | None
    print_code: str | None


class EvaluatorResult(NamedTuple):
    """
    Return type for the evaluator_loop_exp method.

    Attributes
    ----------
    evaluation_output : str | None
        The evaluation output from the code evaluator.
    decision : str | None
        The decision made by the evaluator ("accept" or "reject").
    comment : str | None
        Comments and feedback from the evaluator.
    """

    evaluation_output: str | None
    decision: str | None
    comment: str | None


class CodeGenerationResult(NamedTuple):
    """
    Return type for the generate_code_exp method.

    Attributes
    ----------
    code_output : str
        The final code output generated.
    execution_results : str
        Results from executing the generated code.
    evaluation_output : str
        Output from the code evaluation process.
    """

    code_output: str
    execution_results: str
    evaluation_output: str


class ReportGenerationResult(NamedTuple):
    """
    Return type for the generate_report_exp method.

    Attributes
    ----------
    messages : List[ChatCompletionMessageParam]
        Updated list of chat completion message parameters.
    team_conversation : List[TeamConversationMessage]
        Updated team conversation history with analysis results.
    """

    messages: List[ChatCompletionMessageParam]
    team_conversation: List[TeamConversationMessage]


class WorkflowResult(NamedTuple):
    """Result container for OptiChat workflow execution.

    Contains the final conversation messages and team conversation history
    from a complete workflow execution.
    """

    messages: List[ChatCompletionMessageParam]
    team_conversation: "List[TeamConversationMessage]"


class ParenthesesBalance(NamedTuple):
    """Result container for parentheses balance counting.

    Contains the count of left and right braces at a specific index position.
    """

    left_brace_count: int
    right_brace_count: int


class ModelLoadingResult(NamedTuple):
    """Result container for model loading operations.

    Contains the loaded models container and raw code string.
    """

    models_dict: "ModelsContainer"
    code: str


class FileClassificationResult(NamedTuple):
    """Result container for file classification operations.

    Contains lists of files separated by feasible and infeasible categories.
    """

    infeasible_files: List[str]
    feasible_files: List[str]


class SyntaxGuidanceInternalResult(NamedTuple):
    """Result container for internal syntax guidance operations.

    Contains the generated syntax output and mode information.
    """

    syntax_output: str
    syntax_mode: str


class IndexGuidanceResult(NamedTuple):
    """Result container for index guidance operations.

    Contains the guidance text and mode for handling indexed patterns.
    """

    guidance: str
    mode: str


# TypedDict definitions for model dictionary structures
#
# These type definitions provide structure and documentation for the complex
# nested dictionaries used throughout this module to represent optimization models.
#
# Key Structure Overview:
# - ModelsContainer: Top-level container with "model_representation" and "model_1" keys
# - ModelDictWithPyomo: Individual model dict containing Pyomo objects
#   (not serializable)
# - ModelDictSerializable: Model dict without Pyomo objects (JSON serializable)
# - ComponentsContainer: Nested structure containing sets, parameters, variables, etc.
#
# Note: Some dictionary keys use spaces (e.g., "model status") which limits full
# TypedDict compatibility. These types serve primarily as documentation and partial
# type checking. For complete type safety, consider refactoring to use underscore keys.


class SetComponent(TypedDict):
    """Dictionary structure for optimization model sets."""

    name: str
    is_indexed: bool
    description: str


class ParameterComponent(TypedDict):
    """Dictionary structure for optimization model parameters."""

    name: str
    is_indexed: bool
    index_set: Any  # Pyomo index set object or None
    is_RHS: bool
    is_mutable: bool
    cons_in: Set[str]
    description: str


class ParameterComponentSerializable(TypedDict):
    """Serializable dictionary structure for model parameters (no Pyomo objects)."""

    name: str
    is_indexed: bool
    is_RHS: bool
    is_mutable: bool
    cons_in: Set[str]
    description: str


class VariableComponent(TypedDict):
    """Dictionary structure for optimization model variables."""

    name: str
    is_indexed: bool
    index_set: Any  # Pyomo index set object or None
    cons_in: Set[str]
    description: str


class VariableComponentSerializable(TypedDict):
    """Serializable dictionary structure for model variables (no Pyomo objects)."""

    name: str
    is_indexed: bool
    cons_in: Set[str]
    description: str


class ConstraintComponent(TypedDict):
    """Dictionary structure for optimization model constraints."""

    name: str
    is_indexed: bool
    index_set: Any  # Pyomo index set object or None
    params_in: Set[str]
    vars_in: Set[str]
    description: str


class ConstraintComponentSerializable(TypedDict):
    """Serializable dictionary structure for model constraints (no Pyomo objects)."""

    name: str
    is_indexed: bool
    params_in: Set[str]
    vars_in: Set[str]
    description: str


class ObjectiveComponent(TypedDict):
    """Dictionary structure for optimization model objectives."""

    name: str
    sense: str
    optimal_value: Any  # Can be numeric value or string for infeasible cases
    is_indexed: bool
    description: str


class ComponentsContainer(TypedDict):
    """Dictionary structure for all model components."""

    sets: Dict[str, SetComponent]
    parameters: Dict[str, ParameterComponent]
    variables: Dict[str, VariableComponent]
    constraints: Dict[str, ConstraintComponent]
    objective: Dict[str, ObjectiveComponent]


class ComponentsContainerSerializable(TypedDict):
    """Dictionary structure for model components (serializable, no Pyomo objects)."""

    sets: Dict[str, SetComponent]  # Sets don't have index_set field
    parameters: Dict[str, ParameterComponentSerializable]
    variables: Dict[str, VariableComponentSerializable]
    constraints: Dict[str, ConstraintComponentSerializable]
    objective: Dict[str, ObjectiveComponent]  # Objectives don't have index_set


class IISConstraint(TypedDict):
    """Dictionary structure for IIS constraint information."""

    params_in: Set[str]
    vars_in: Set[str]


class ModelDictWithPyomo(TypedDict):
    """
    Dictionary structure for a complete optimization model with Pyomo objects.

    Uses underscore keys for proper TypedDict support:
    - model_class: Pyomo ConcreteModel object
    - model_status: Solver termination condition
    - model_type: Problem type ("LP", "IP", etc.)
    - model_description: Model description string
    - components: Nested dict with sets, parameters, variables, constraints, objective
    - code: Source code string
    - iis: Optional IIS constraint information
    - iis_description: Optional IIS description string
    """

    # Required fields from pyomo2json
    model_class: pe.ConcreteModel
    model_status: str
    model_type: str
    model_description: Any
    components: ComponentsContainer

    # Added in initial_loading
    code: str

    # Optional fields added conditionally
    iis: NotRequired[Dict[str, IISConstraint]]
    iis_description: NotRequired[str]


class ModelDictSerializable(TypedDict):
    """
    Dictionary structure for a serializable optimization model (no Pyomo objects).

    Same as ModelDictWithPyomo but excludes model_class and uses serializable
    components that don't contain index_set fields with Pyomo objects.

    Uses underscore keys for proper TypedDict support:
    - model_status: Solver termination condition
    - model_type: Problem type ("LP", "IP", etc.)
    - model_description: Model description string
    - components: Serializable nested dict with model components
    - code: Source code string
    - iis: Optional IIS constraint information
    - iis_description: Optional IIS description string
    """

    # Required fields (no model_class since it's not serializable)
    model_status: str
    model_type: str
    model_description: Any
    components: ComponentsContainerSerializable

    # Added in initial_loading
    code: str

    # Optional fields added conditionally
    iis: NotRequired[Dict[str, IISConstraint]]
    iis_description: NotRequired[str]


# For the main models container
ModelsContainer = Dict[str, ModelDictWithPyomo]
